var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var PostSchema = new Schema({
    id: {
        type: String //this is autogenerated by mongodb
    },
    title: {
        type: String
    },
    dateTime: {
        type: Date,
        default: Date.now
    },
    description: {
        type: String
    },
    username: { //change this to a user // user
        type: String
    },
    photo: {
        //should be a jpeg 
        type: String,
        required: "Please select a picture for your post"
    }
});
module.exports = mongoose.model('Post', PostSchema);
